// dev/vue/src/all.vue
<script setup lang="ts">
import { ref } from "vue";

const components = import.meta.glob("../../../website/codemos/**/*.vue", {
  import: "default",
  eager: true,
});

const parentDir = "../../../website/codemos/";
const result: Record<string, Record<string, any>> = {};

for (const [path, Comp] of Object.entries(components)) {
  const k = path.replace(parentDir, "");
  const bb = k.split("/");
  const section = bb[0];
  result[section] = result[section] || {};
  result[section][bb[1]] = Comp;
}

const active = ref("input");

const sidebarLinks = Object.keys(result)
</script>

<template>
  <main class="m10">
    <aside class="flex gap3">
      <button
        v-for="section in sidebarLinks"
        :key="section"
        class="capitalize"
        :class='active === section ? "btn-primary" : "btn"'
        @click="active = section"
      >
        {{ section }}
      </button>
    </aside>

    <section class="grid gap5 my10">
      <div
        v-for="([path, Comp]) in Object.entries(result[active])"
        :key="path"
        class="grid gap3"
      >
        <h3 class="capitalize">{{ path.split(".")[0] }}</h3>

        <div class="demobox justify-start !p5">
          <component :is="Comp" />
        </div>
      </div>
    </section>
  </main>
</template>

// dev/react/src/all.tsx
import { useState } from "react";

const components = import.meta.glob("../../../website/codemos/**/*.jsx", {
  import: "default",
  eager: true,
});

const parentDir = "../../../website/codemos/";
let result: any = {};

for (const [path, Comp] of Object.entries(components)) {
  const k = path.replace(parentDir, "");
  const bb = k.split("/");
  const section = bb[0];
  result[section] = result[section] || {};
  result[section][bb[1]] = Comp;
}

export default () => {
  const [active, setActive] = useState("btn");

  return (
    <main className="m10">
      <aside className="flex gap3">
        {Object.keys(result).map((section) => (
          <button
            className={` capitalize ${active == section ? "btn-primary" : "btn"}`}
            onClick={() => setActive(section)}
          >
            {section}
          </button>
        ))}
      </aside>

      <section className="grid gap5 my10">
        {Object.entries(result[active]).map(([path, Comp]) => (
          <div className="grid gap3">
            <h3 className="capitalize">{path.split(".")[0]}</h3>

            <div className="demobox justify-start !p5">
              <Comp key={path} />
            </div>
          </div>
        ))}
      </section>
    </main>
  );
};
