// dev/react/src/main.tsx
import { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";
// @ts-ignore
import "../../shared/style.css";
// @ts-ignore
import "virtual:uno.css";
// import "@unocss/reset/tailwind.css";
import { Btn, Tabs, Tab, TabsContent, TabsList } from "@haze-ui/react";

function App() {
  const [val, setVal] = useState();

  return (
    <main className="gid gap4 items-center p5">
      <Btn txt="hi" className="btn-outline bg-red" />

      <br />
      <br />
      <br />

          <input type="checkbox" className="switch-line" />
          <input type="checkbox" className="switch" />
      <br />
      <br />

      <Tabs value={val} setValue={setVal}>
        <TabsList className="tabs">
          <Tab value="preview">Preview</Tab>
          <Tab value="code">Code</Tab>
        </TabsList>

        <TabsContent value="preview">
          <div className="p4 rounded brd mt9">some preview here</div>
        </TabsContent>

        <TabsContent value="code">
          <div className="p4 rounded brd mt9">some code here</div>
        </TabsContent>
      </Tabs>
    </main>
  );
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);

// dev/solid/src/main.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import { createSignal, createEffect, onMount } from "solid-js";

// @ts-ignore
import "virtual:uno.css";
// @ts-ignore
import "../../shared/style.css";

// import { Userpic, Btn} from "../../../packages/solid/index";
import { Btn, Tabs, Tab, TabsContent, TabsList } from "@haze-ui/solid";

function App() {
  const [val, setVal] = createSignal();

  return (
    <main class="gid gap4 items-center p5">
      <input class="input-outline" />
      <Btn txt="hello" class="btn-blue" />
      <br />
      <br />

      <Tabs setValue={setVal} value={val}>
        <TabsList class="tabs-outline">
          <Tab value="preview">Preview</Tab>
          <Tab value="code">Code</Tab>
        </TabsList>

        <div class="p4 rounded brd mt9">
          {val() == "preview" && <div>some preview here</div>}
          {val() == "code" && <div>some code here</div>}
        </div>
      </Tabs>
    </main>
  );
}

const root = document.getElementById("root");
render(() => <App />, root!);
