// packages/vue/src/dropdown/trigger.vue
<script setup lang="ts">
import { type ButtonHTMLAttributes, inject } from "vue";
import type { PassedProps } from "./types";

let ctx = inject("dropdown") as PassedProps;

let { class: css = "" } = defineProps</* @vue-ignore */ ButtonHTMLAttributes>();
</script>

<template>
  <button
    :ref="ctx.btnref"
    :class='`${css?.includes("btn") ? "" : "btn"} ${css}`'
    @click="ctx.toggleDropdown"
  >
    <slot />
  </button>
</template>

// packages/svelte/src/dropdown/trigger.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import type { HTMLButtonAttributes } from "svelte/elements";
  import type { PassedProps } from "./types";

  let ctx = getContext("dropdown") as PassedProps;

  let { children, class: css, ...rest }: HTMLButtonAttributes = $props();
</script>

<button
  bind:this={ctx.ref}
  class={css?.includes("btn") ? css : `btn ${css}`}
  onclick={ctx.toggleDropdown}
  {...rest}
>
  {@render children?.()}
</button>
