// packages/react/src/button.tsx
import { type BtnProps } from "types/button";

type Props = BtnProps & React.ButtonHTMLAttributes<HTMLButtonElement>;

const Btn = ({
  iconL,
  iconR,
  txt,
  loading,
  loaderTxt,
  className = "",
  variant = "primary",
  ...x
}: Props) => {
  const variants: any = {
    primary: "btn-primary",
    soft: "btn-soft",
    outline: "btn-outline",
    ghost: "btn-ghost",
  };

  const css = `${variants[variant]} ${className}`;

  return (
    <button className={css} {...x}>
      {iconL && <div className={iconL} />}
      {loading && <div className="i-eos-icons:loading text-sm" />}
      {txt && !loading && txt}
      {loading && loaderTxt && loaderTxt}
      {iconR && <div className={iconR} />}
    </button>
  );
};

export default Btn;

// packages/svelte/src/button.svelte
<script lang="ts">
  import type { HTMLButtonAttributes } from "svelte/elements";
  import type { BtnProps } from "types/button";

  type Props = BtnProps & HTMLButtonAttributes;

  let {
    txt,
    iconL,
    iconR,
    loading,
    loaderTxt,
    class: myclass,
    variant = "primary",
    ...x
  }: Props = $props();

  const variants: any = {
    primary: "btn-primary",
    soft: "btn-soft",
    ghost: "btn-ghost",
    outline: "btn-outline",
  };

  const css = `${variants[variant]} ${myclass}`;
</script>

<button class={css} {...x}>
  {#if iconL}
    <div class={iconL}></div>
  {/if}

  {#if loading}
    <div class="i-eos-icons:loading"></div>
  {/if}

  {#if txt && !loading}
    {txt}
  {/if}

  {#if loading && loaderTxt}
    {loaderTxt}
  {/if}

  {#if iconR}
    <div class={iconR}></div>
  {/if}
</button>
