// website/codemos/input/size.svelte
<script lang="ts">
  import { Input } from "@haze-ui/svelte";
</script>

<div class="grid-(~ gap5 wrap) items-center brd p5 rounded">
  <Input placeholder="size (sm)" class="grinput-sm" />
  <Input placeholder="size (md)" class="grinput-md" />
  <Input placeholder="size (lg)" class="grinput-lg" />
  <Input placeholder="size (xl)" class="grinput-outline-xl" />
</div>

// website/codemos/input/size.jsx
import { Input } from "@haze-ui/react";

export default () => {
  return (
    <>
      <Input placeholder="size (sm)" className="grinput-sm" />
      <Input placeholder="size (md)" className="grinput-md" />
      <Input placeholder="size (lg)" className="grinput-lg" />
      <Input placeholder="size (xl)" className="grinput-outline-xl" />
    </>
  );
};
