// website/codemos/input/size.jsx
import { Input } from "@haze-ui/react";

export default () => {
  return (
    <>
      <Input placeholder="size (sm)" className="grinput-sm" />
      <Input placeholder="size (md)" className="grinput-md" />
      <Input placeholder="size (lg)" className="grinput-lg" />
      <Input placeholder="size (xl)" className="grinput-outline-xl" />
    </>
  );
};

// website/codemos/input/size.vue
<script setup>
import { Input } from "@haze-ui/vue";
</script>

<template>
  <Input placeholder="size (sm)" class="grinput-sm" />
  <Input placeholder="size (md)" class="grinput-md" />
  <Input placeholder="size (lg)" class="grinput-lg" />
  <Input placeholder="size (xl)" class="grinput-outline-xl" />
</template>
