// website/codemos/dialog/usage.jsx
import { useState } from "react";
import { Dialog } from "@haze-ui/react";

export default () => {
  const [open, setOpen] = useState(false);
  const openDialog = () => setOpen(true);
  const closeDialog = () => setOpen(false);

  return (
    <>
      <button className="btn-primary mx-auto" onClick={openDialog}>
        Open
      </button>

      <Dialog open={open} close={closeDialog} className="grid gap4">
        <h3>Edit Account</h3>

        <p className="text-muted-fg mb2">
          Make changes to your user profile here.
        </p>

        <label htmlFor="name">Name</label>
        <input
          className="input-outline"
          id="name"
          placeholder="Enter your name"
        />

        <label htmlFor="email">Email</label>
        <input
          type="email"
          className="input-outline"
          id="email"
          placeholder="Enter your email"
        />

        <div className="flex gap3 items-center ml-auto mt3">
          <button className="btn-soft" onClick={closeDialog}>
            Cancel
          </button>
          <button className="btn-primary">Save</button>
        </div>
      </Dialog>
    </>
  );
};

// website/codemos/dialog/usage.vue
<script setup>
import { ref } from "vue";
import { Dialog } from "@haze-ui/vue";

const open = ref(false);
const openDialog = () => (open.value = true);
const closeDialog = () => (open.value = false);
</script>

<template>
  <button class="btn-primary mx-auto" @click="openDialog">
    Open
  </button>

  <Dialog :open="open" :close="closeDialog" class="grid gap4">
    <h3>Edit Account</h3>

    <p class="text-muted-fg mb2">
      Make changes to your user profile here.
    </p>

    <label for="name">Name</label>
    <input
      class="input-outline"
      id="name"
      placeholder="Enter your name"
    />

    <label for="email">Email</label>
    <input
      type="email"
      class="input-outline"
      id="email"
      placeholder="Enter your email"
    />

    <div class="flex gap3 items-center ml-auto mt3">
      <button class="btn-soft" @click="closeDialog">
        Cancel
      </button>
      <button class="btn-primary">Save</button>
    </div>
  </Dialog>
</template>
