// website/codemos/tabs/usage.jsx
import { Tab, Tabs, TabsContent, TabsList } from "@haze-ui/react";

export default () => {
  const tabStyles = [
    "tabs-box",
    "tabs-classic",
    "tabs-outline",
    "tabs-line",
    "tabs-subtle",
  ];

  return (
    <div className="grid gap3">
      {tabStyles.map((tabStyle) => (
        <Tabs key={tabStyle}>
          <TabsList className={tabStyle}>
            <Tab value="account">
              <i className="i-line-md:account" /> Account
            </Tab>
            <Tab value="settings">
              <i className="i-mynaui:cog-two" /> Settings
            </Tab>
            <Tab value="Network">
              <i className="i-eos-icons:network" /> Network
            </Tab>
          </TabsList>

          <div className="rounded bg-input p10 shadow-md brd flex justify-center">
            <TabsContent value="account">Account content</TabsContent>
            <TabsContent value="settings">Settings content</TabsContent>
            <TabsContent value="Network">Network content</TabsContent>
          </div>
        </Tabs>
      ))}
    </div>
  );
};

// website/codemos/tabs/usage.vue
<script setup>
import { Tab, Tabs, TabsContent, TabsList } from "@haze-ui/vue";

const tabStyles = ["tabs-box", "tabs-classic", "tabs-outline", "tabs-line", "tabs-subtle"];
</script>

<template>
  <div v-for="tabStyle in tabStyles" :key="tabStyle" class="grid gap3">
    <Tabs>
      <TabsList :class="tabStyle">
        <Tab value="account">
          <i class="i-line-md:account"></i> Account
        </Tab>
        <Tab value="settings">
          <i class="i-mynaui:cog-two"></i> Settings
        </Tab>
        <Tab value="Network">
          <i class="i-eos-icons:network"></i> Network
        </Tab>
      </TabsList>

      <div class="rounded bg-input p10 shadow-md brd flex justify-center">
        <TabsContent value="account">
          Account content
        </TabsContent>
        <TabsContent value="settings">
          Settings content
        </TabsContent>
        <TabsContent value="Network">
          Network content
        </TabsContent>
      </div>
    </Tabs>
  </div>
</template>
