// website/codemos/btn/variant.svelte
<script lang="ts">
  import { Btn } from "@haze-ui/svelte";
</script>

<div class="flex-(~ gap3 wrap) items-center brd p5 rounded">
  <Btn txt="Primary" class="btn-primary" />
  <Btn class="soft" txt="Soft" />
  <Btn class="btn-outline" txt="Outline" />
  <Btn class="btn-ghost" txt="Ghost" />
</div>

// website/codemos/toast/variant.jsx
import { toast } from "@haze-ui/react";

const newToast = (css) => {
  toast({
    title: "Toast Activated",
    txt: "Customize this text to suit your message",
    css: css,
  });
};

export default () => {
  return (
    <div className="flex flex-wrap gap-2">
      <button className="btn-primary" onClick={() => newToast("toast-solid")}>
        Solid
      </button>

      <button className="btn" onClick={() => newToast("toast-flat")}>
        Flat
      </button>

      <button className="btn-outline" onClick={() => newToast("toast-outline")}>
        Outline
      </button>
    </div>
  );
};
