// packages/solid/components/switch.tsx
import { ComponentProps, splitProps } from "solid-js";
import { SwitchProps } from "types/switch";

type Props = SwitchProps & ComponentProps<"input">;

export default (x: Props) => {
  const [local, others] = splitProps(x, ["knobcss", "class"]);

  return (
    <label class={local.class || "switch"}>
      <input type="checkbox" class="peer" {...others} />
      <span class={local.knobcss || "swdot"}></span>
    </label>
  );
};

// packages/react/src/switch.tsx
import { type SwitchProps } from "types/switch";

type Props = SwitchProps & React.InputHTMLAttributes<HTMLInputElement>;

export default ({ className, knobcss = "", ...restProps }: Props) => {
  return (
    <label className={className || "switch"}>
      <input type="checkbox" className="peer" {...restProps} />
      <span className={knobcss || "swdot"}></span>
    </label>
  );
};
