// packages/svelte/src/switch.svelte
<script lang="ts">
  import type { SwitchProps } from "types/switch";
  import type { HTMLInputAttributes } from "svelte/elements";
  type Props = SwitchProps & HTMLInputAttributes;

  let { class: css, knobcss, ...restProps } = $props() as Props;
</script>

<label class={css || "switch"}>
  <input type="checkbox" class="peer" {...restProps} />
  <span class={knobcss || "swdot"}></span>
</label>

// packages/react/src/switch.tsx
import { type SwitchProps } from "types/switch";

type Props = SwitchProps & React.InputHTMLAttributes<HTMLInputElement>;

export default ({ className, knobcss = "", ...restProps }: Props) => {
  return (
    <label className={className || "switch"}>
      <input type="checkbox" className="peer" {...restProps} />
      <span className={knobcss || "swdot"}></span>
    </label>
  );
};
