// packages/solid/src/tabs.tsx
import { createSignal, createContext } from "solid-js";
import { useContext, onMount, Show } from "solid-js";
import type { TabsProps } from "types/tabs";

type CtxProps = {
  value: () => string;
  tabLabels: () => string[];
  setValue: (x: any) => void;
  setTabLabels: (x: any) => void;
};

const context = createContext<CtxProps | null>(null);

export const TabsList = (x: any) => {
  const { value, tabLabels, setValue } = useContext(context) as CtxProps;
  const activeIndex = () => tabLabels().indexOf(value());

  const handleKeyDown = (e: KeyboardEvent) => {
    e.preventDefault();
    const currentIndex = activeIndex();
    if (e.key === "ArrowLeft" && currentIndex !== 0) {
      setValue(tabLabels()[currentIndex - 1]);
    } else if (
      e.key === "ArrowRight" &&
      currentIndex !== tabLabels().length - 1
    ) {
      setValue(tabLabels()[currentIndex + 1]);
    }
  };

  onMount(() => {});

  return (
    <div
      role="tablist"
      class={x?.class?.includes("tabs-") ? x.class : `tabs ${x.class}`}
      onKeyDown={handleKeyDown}
      tabIndex={-1}
    >
      {x.children}
    </div>
  );
};

interface Props {
  value: string;
  children: any;
  class?: string;
}

export const Tab = (x: Props) => {
  const { value, setValue, setTabLabels } = useContext(context) as CtxProps;
  const setActiveTab = () => setValue(x.value);

  onMount(() => {
    setTabLabels((prev: any) => {
      if (!value()) setValue(x.value);
      return [...prev, x.value];
    });
  });

  return (
    <button
      role="tab"
      onClick={setActiveTab}
      aria-selected={value() === x.value}
    >
      {x.children}
    </button>
  );
};

export const TabsContent = (x: Props) => {
  const { value } = useContext(context) as CtxProps;

  return (
    <Show when={value() === x.value}>
      <div
        role="tabpanel"
        aria-labelledby={`tab-${value()}`}
        class={x.class || ""}
      >
        {x.children}
      </div>
    </Show>
  );
};

export const Tabs = (x: TabsProps) => {
  const [va, setVal] = createSignal(x.defaultValue);
  const [tabLabels, setTabLabels] = createSignal([]);

  const ctxValue: CtxProps = {
    value: x.value ?? va,
    setValue: x.setValue ?? setVal,
    tabLabels,
    setTabLabels,
  };

  return <context.Provider value={ctxValue}>{x.children}</context.Provider>;
};

// packages/react/src/tabs.tsx
import { useState, useContext } from "react";
import { createContext, useEffect, type KeyboardEvent } from "react";

import type { TabsProps } from "types/tabs";

type CtxProps = {
  value: string | undefined;
  tabLabels: string[];
  setValue: (x: any) => void;
  setTabLabels: (x: any) => void;
};

const context = createContext<CtxProps | null>(null);

interface Props {
  value?: string;
  children: any;
  className?: string;
}

const TabsList = ({ children, className = "" }: Props) => {
  const { value, tabLabels, setValue } = useContext(context) as CtxProps;

  let activeIndex = tabLabels.indexOf(value || tabLabels[0]);

  const handleKeyDown = (e: KeyboardEvent) => {
    e.preventDefault();

    if (e.key == "ArrowLeft" && activeIndex != 0) {
      setValue(tabLabels[activeIndex - 1]);
    } //
    else if (e.key == "ArrowRight" && activeIndex != tabLabels.length - 1) {
      setValue(tabLabels[activeIndex + 1]);
    }
  };

  useEffect(() => {
    if (!value) setValue(tabLabels[0]);
  }, [tabLabels]);

  return (
    <div
      role="tablist"
      className={className.includes("tabs-") ? className : `tabs ${className}`}
      onKeyDown={handleKeyDown}
      tabIndex={-1}
    >
      {children}
    </div>
  );
};

type TabProps = {
  iconL?: string;
  value: string;
} & React.ButtonHTMLAttributes<HTMLButtonElement>;

const Tab = ({ iconL, value, children }: TabProps) => {
  const {
    value: active,
    setValue,
    setTabLabels,
  } = useContext(context) as CtxProps;

  const setActiveTab = () => setValue(value);

  useEffect(() => {
    setTabLabels((prev: any) => [...new Set([...prev, value])]);
  }, []);

  return (
    <button role="tab" onClick={setActiveTab} aria-selected={active == value}>
      {iconL && <span className={iconL}></span>}
      {children}
    </button>
  );
};

const TabsContent = ({ value, children }: Props) => {
  const { value: curval } = useContext(context) as CtxProps;

  return curval == value ? (
    <div role="tabpanel" aria-labelledby={`tab-${curval}`}>
      {children}
    </div>
  ) : null;
};

const Tabs = ({ children, defaultValue, value, setValue }: TabsProps) => {
  const [val, setVal] = useState(defaultValue);
  const [tabLabels, setTabLabels] = useState([]);

  const ctxValue: CtxProps = {
    value: value ?? val,
    setValue: setValue ?? setVal,
    tabLabels,
    setTabLabels,
  };

  return <context.Provider value={ctxValue}>{children}</context.Provider>;
};

export { Tabs, TabsList, Tab, TabsContent };
