// packages/react/src/button.tsx
import { type BtnProps } from "types/button";

type Props = BtnProps & React.ButtonHTMLAttributes<HTMLButtonElement>;

const Btn = ({
  iconL,
  iconR,
  txt,
  loading,
  loaderTxt,
  className = "",
  ...x
}: Props) => {
  const css = `${className?.includes("btn-") ? "" : "btn-soft"} ${className}`;

  return (
    <button className={css} {...x}>
      {iconL && <div className={iconL} />}
      {loading && <div className="i-eos-icons:loading text-sm" />}
      {txt && !loading && txt}
      {loading && loaderTxt && loaderTxt}
      {iconR && <div className={iconR} />}
    </button>
  );
};

export default Btn;

// packages/vue/src/button.vue
<script setup lang="ts">
import type { ButtonHTMLAttributes } from "vue";
import type { BtnProps } from "types/button";

type Props = BtnProps & /* @vue-ignore */ ButtonHTMLAttributes;

const {
  txt,
  iconL,
  iconR,
  loading,
  loaderTxt,
  class: css,
} = defineProps<Props>();
</script>

<template>
  <button :class="`${css?.includes('btn-') ? '' : 'btn'} ${css}`">
    <div :class="iconL" v-if="iconL"></div>
    <div v-if="loading" class="i-eos-icons:loading" />
    <div v-if="loading && loaderTxt">{{ loaderTxt }}</div>
    <div v-if="txt && !loading">{{ txt }}</div>
    <div :class="iconR" v-if="iconR" />
  </button>
</template>
