// packages/solid/components/input.tsx
import { ComponentProps, JSX } from "solid-js";

type Props = {
  variant?: "outline" | "solid";
  iconL?: string | JSX.Element;
  iconR?: string | JSX.Element;
  disabled?: boolean;
  class?: string;
  parentCss?: string;
} & ComponentProps<"input">;

const Input = (x: Props) => {
  const variants = {
    outline: "outline-(1 solid border)",
    solid: "bg-input",
  };

  const css = `bg-bg rounded flex items-center gap1 p1
    px3 duration-150 focus-within:ring-(2 primary)
    ${x.disabled ? "brightness-95" : ""} ${variants[x.variant ?? "outline"]} ${x.parentCss ?? ""}`;

  const inputCss = `p2 border-0 outline-0 w-full
    ${x.variant === "solid" ? "bg-input" : "bg-bg"} ${x.class ?? ""}`;

  return (
    <div class={css}>
      {x.iconL && typeof x.iconL === "string" ? <div class={x.iconL} /> : x.iconL}

      <input {...x} class={inputCss} disabled={x.disabled} />

      {x.iconR && typeof x.iconR === "string" ? <div class={x.iconR} /> : x.iconR}
    </div>
  );
};

export default Input;

// packages/react/components/input.tsx
import React from "react";

interface Props extends React.InputHTMLAttributes<HTMLInputElement> {
  variant?: "outline" | "solid";
  iconL?: string | React.ReactNode;
  iconR?: string | React.ReactNode;
  disabled?: boolean;
  className?: string;
  parentCss?: string;
  [x: string]: any;
}

const Input = ({
  className,
  variant = "outline",
  iconL,
  iconR,
  parentCss = "",
  disabled,
  ...x
}: Props) => {
  const variants = { outline: "outline-(1 solid border)", solid: "bg-input" };

  const css = `bg-bg rounded flex items-center gap1 p1
            px3 duration-150 focus-within:ring-(2 primary)
            ${disabled ? "brightness-95" : ""} ${variants[variant]} ${parentCss}`;

  const inputCss = `p2 border-0 outline-0 w-full
                    ${variant == "solid" ? "bg-input" : "bg-bg"} ${className}`;

  return (
    <div className={css}>
      {iconL && typeof iconL == "string" ? <div className={iconL} /> : iconL}

      <input {...x} disabled={disabled} className={inputCss} />

      {iconR && typeof iconR == "string" ? <div className={iconR} /> : iconR}
    </div>
  );
};

export default Input;
