// packages/svelte/src/dialog.svelte
<script lang="ts">
  import { portal } from "./portal";
  import type { HTMLAttributes } from "svelte/elements";
  import type { DialogProps } from "types/dialog";

  type Props = DialogProps & HTMLAttributes<HTMLElement>;

  let { open, close, class: myclass, children, closeIcon = true }: Props =
    $props();

  let ref: HTMLDialogElement = $state();

  const handlekeydown = (e: KeyboardEvent) => {
    if (e.key === "Escape") {
      close();
      return;
    }

    if (e.key === "Tab") {
      const focusableElements = ref.querySelectorAll<HTMLElement>(
        'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
      );

      if (focusableElements.length === 0) return;

      const firstElement = focusableElements[0];
      const lastElement = focusableElements[focusableElements.length - 1];

      if (e.shiftKey && document.activeElement === firstElement) {
        e.preventDefault();
        lastElement.focus();
      } else if (!e.shiftKey && document.activeElement === lastElement) {
        e.preventDefault();
        firstElement.focus();
      }
    }
  };

  const stopPropagation = (e: Event) => e.stopPropagation();

  $effect(() => {
    if (open) ref?.showModal();
  });
</script>

{#if open}
  <dialog
    class="backdrop:bg-black/60"
    use:portal
    bind:this={ref}
    onclick={close}
  >
    <div
      role="dialog"
      tabindex="-1"
      onkeydown={handlekeydown}
      class={`dialog ${myclass}`}
      onclick={stopPropagation}
    >
      {#if closeIcon}
        <button
          class="i-pajamas:close absolute right-4 top-4 focus:bg-red"
          aria-label="close"
          onclick={close}
          tabindex="-1"
        >
        </button>
      {/if}

      {@render children()}
    </div>
  </dialog>
{/if}

// packages/solid/src/dialog.tsx
import { createEffect, type ComponentProps, Show } from "solid-js";
import { Portal, mergeProps } from "solid-js/web";

import { type DialogProps } from "types/dialog";

type Props = DialogProps & ComponentProps<"dialog">;

const Dialog = (props: Props) => {
  props = mergeProps({ closeIcon: true }, props);

  let ref: HTMLDialogElement | undefined;

  createEffect(() => {
    if (props.open) ref?.showModal();
  });

  const handlekeydown = (e: KeyboardEvent) => {
    if (e.key === "Escape") {
      close();
      return;
    }

    if (e.key === "Tab") {
      const focusableElements = ref?.querySelectorAll<HTMLElement>(
        'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
      );

      if (!focusableElements || focusableElements?.length === 0) return;

      const firstElement = focusableElements[0];
      const lastElement = focusableElements[focusableElements.length - 1];

      if (e.shiftKey && document.activeElement === firstElement) {
        e.preventDefault();
        lastElement.focus();
      } else if (!e.shiftKey && document.activeElement === lastElement) {
        e.preventDefault();
        firstElement.focus();
      }
    }
  };

  const stopPropagation = (e: Event) => e.stopPropagation();

  return (
    <Portal>
      <dialog ref={ref} class="backdrop:bg-black/60" onclick={props.close}>
        <div
          role="dialog"
          onKeyDown={handlekeydown}
          class={`dialog ${props.class ?? ""}`}
          onClick={stopPropagation}
        >
          {props.closeIcon && (
            <button
              class="i-pajamas:close absolute right-4 top-4 focus-visible:bg-red"
              aria-label="close"
              tabindex="-1"
              tabIndex={-1}
              onClick={close}
            ></button>
          )}
          {props.children}
        </div>
      </dialog>
    </Portal>
  );
};

export default (props: Props) => (
  <Show when={props.open}>
    <Dialog {...props} />
  </Show>
);
