// dev/svelte/src/App.svelte
<script lang="ts">
  import "virtual:uno.css";
  import "../../shared/style.css";
  // import Btn from "haze-ui/button.svelte";
  // import Input from "haze-ui/input.svelte";

  import { Switch } from "../../../packages/svelte/src/index";
  import Test from "./test.svelte";
</script>

<main class="m-10">
  <Switch />
  <Test />
</main>

// dev/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";

import All from "./all.vue";
import { Input } from "@haze-ui/vue";

const path = window.location.pathname;

// import Btn from "../../../packages/vue/src/button.vue"
</script>

<template>
  <a v-if='path == "/"' class="btn" href="/all">go to /all</a>
  <All v-else />
</template>
