// website/codemos/dropdown/usage.svelte
<script lang="ts">
  import {
    Dropdown,
    DropdownContent,
    DropdownItem,
    DropdownTrigger,
  } from "@haze-ui/svelte";
</script>

<Dropdown>
  <DropdownTrigger class="btn-primary"> Click me</DropdownTrigger>

  <DropdownContent>
    <DropdownItem>Profile</DropdownItem>
    <DropdownItem>Billing</DropdownItem>
    <DropdownItem>Settings</DropdownItem>
    <DropdownItem>Keyboard shortcuts </DropdownItem>
    <hr class="brd my1" />

    <DropdownItem>Team</DropdownItem>
    <DropdownItem>Invite users</DropdownItem>
    <DropdownItem>New Team</DropdownItem>
    <hr class="brd my1" />

    <DropdownItem>GitHub</DropdownItem>
    <DropdownItem>Support</DropdownItem>
    <DropdownItem disabled={true}>API</DropdownItem>

    <hr class="brd my1" />
    <DropdownItem>Log out</DropdownItem>
  </DropdownContent>
</Dropdown>

<Dropdown>
  <DropdownTrigger class="btn-soft">
    <i class="i-line-md:star-filled"></i>
    With icons
  </DropdownTrigger>

  <DropdownContent>
    <DropdownItem> <i class="i-line-md:account"></i>Profile</DropdownItem>
    <DropdownItem><i class="i-nimbus:cog"></i>Settings</DropdownItem>
    <DropdownItem> <i class="i-line-md:logout"></i>Log out</DropdownItem>
  </DropdownContent>
</Dropdown>

// website/codemos/dropdown/usage.jsx
import {
  Dropdown,
  DropdownContent,
  DropdownItem,
  DropdownTrigger,
} from "@haze-ui/react";

export default () => {
  <>
    <Dropdown>
      <DropdownTrigger> Dropdown</DropdownTrigger>

      <DropdownContent>
        <DropdownItem>Profile</DropdownItem>
        <DropdownItem>Billing</DropdownItem>
        <DropdownItem>Settings</DropdownItem>
        <DropdownItem>Keyboard shortcuts </DropdownItem>
        <hr className="brd my1" />

        <DropdownItem>Team</DropdownItem>
        <DropdownItem>Invite users</DropdownItem>
        <DropdownItem>New Team</DropdownItem>
        <hr className="brd my1" />

        <DropdownItem>GitHub</DropdownItem>
        <DropdownItem>Support</DropdownItem>
        <DropdownItem disabled={true}>API</DropdownItem>

        <hr className="brd my1" />
        <DropdownItem>Log out</DropdownItem>
      </DropdownContent>
    </Dropdown>

    <Dropdown>
      <DropdownTrigger className="btn-soft">
        <i className="i-line-md:star-filled"></i>
        With icons
      </DropdownTrigger>

      <DropdownContent>
        <DropdownItem>
          <i className="i-line-md:account"></i>Profile
        </DropdownItem>
        <DropdownItem>
          <i className="i-nimbus:cog"></i>Settings
        </DropdownItem>
        <DropdownItem>
          <i className="i-line-md:logout"></i>Log out
        </DropdownItem>
      </DropdownContent>
    </Dropdown>
  </>;
};
