// packages/vue/src/dropdown/item.vue
<script setup lang="ts">
import { type ButtonHTMLAttributes, inject } from "vue";
import type { PassedProps } from "./types";

let ctx = inject("dropdown") as PassedProps;
let { class: css = "" } = defineProps</* @vue-ignore */ ButtonHTMLAttributes>();
</script>

<template>
  <button
    role='menuitem'
    :class="`btn-ghost-eqmd focus:bg-input justify-start whitespace-nowrap ${css}`"
    @click="ctx.closeDropdown"
  >
    <slot />
  </button>
</template>

// packages/svelte/components/dropdown/item.svelte
<script lang="ts">
  import type { PassedProps } from "./types";
  import { getContext } from "svelte";
  
  interface Props {
    class?: string;
    children?: any;
  }
  
  let { children, class: css, ...rest }: Props = $props();
  const { closeDropdown } = getContext("dropdown") as PassedProps;
</script>

<button
  onclick={closeDropdown}
  class={`btn-ghost-eqmd justify-start whitespace-nowrap ${css}`}
  role="menuitem"
  {...rest}
>
  {@render children?.()}
</button>
