// packages/vue/src/tabs/content.vue
<script setup lang="ts">
import { inject } from "vue";
import type { CtxProps } from "./types";

type Props = {
  value: string;
  class?: string;
};

const props = defineProps<Props>();
const ctx = inject("tabs") as CtxProps;
</script>

<template>
  <div
    v-if="props.value === ctx.value.value"
    role="tabpanel"
    :class="props.class"
    :aria-labelledby="`tab-${props.value}`"
    :id="`panel-${props.value}`"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/tabs/content.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import type { CtxProps } from "./index.svelte";

  let { children, value } = $props();

  const { value: active } = getContext("tabs") as CtxProps;
</script>

{#if active() == value}
  <div role="tabpanel" aria-labelledby={`tab-${active()}`}>
    {@render children()}
  </div>
{/if}
