// packages/vue/src/tabs/index.vue
<script setup lang="ts">
import type { TabsProps } from "types/tabs";
import { provide, ref } from "vue";

const { defaultValue, value, setValue } = defineProps<TabsProps>();

let active = ref(defaultValue);
let tabLabels = ref<string[]>([]);

const setActive = (x: string) => active.value = x;

provide("tabs", {
  value: value ?? active,
  setValue: setValue ?? setActive,
  tabLabels: tabLabels,
  addTabLabel: (x: string) => tabLabels.value.push(x),
});
</script>

<template>
  <slot />
</template>

// packages/svelte/src/tabs/index.svelte
<script lang="ts" module>
  import type { TabsProps } from "types/tabs";

  export interface CtxProps {
    value: () => string;
    tabLabels: () => string[];
    setValue: (x: string) => void;
    addTabLabel: (x: string[]) => void;
  }
</script>

<script lang="ts">
  import { setContext } from "svelte";
  let { children, defaultValue, value, setValue }: TabsProps = $props();

  let active = $state(defaultValue);
  let tabLabels: string[] = $state([]);

  const setActive = (x: string) => active = x;

  setContext("tabs", {
    value: () => value ?? active,
    setValue: setValue ?? setActive,
    tabLabels: () => tabLabels,
    addTabLabel: (x: string) => tabLabels.push(x),
  });
</script>

{@render children()}
