// packages/vue/src/tabs/tab.vue
<script lang="ts" setup>
import { inject } from "vue";

import type { CtxProps } from "./types";

let { value } = defineProps<{ value: string }>();

const ctx = inject("tabs") as CtxProps;
const setActiveTab = () => ctx.setValue(value);

ctx.addTabLabel(value);
</script>

<template>
  <button
    role="tab"
    @click="setActiveTab"
    :aria-selected="ctx.value.value == value"
  >
    <slot />
  </button>
</template>

// packages/svelte/src/tabs/tab.svelte
<script lang="ts">
  import { getContext, onMount } from "svelte";
  import type { CtxProps } from "./index.svelte";

  let { children, value } = $props();

  const { value: active, setValue, addTabLabel } = getContext(
    "tabs",
  ) as CtxProps;

  const setActiveTab = () => setValue(value);

  onMount(() => addTabLabel(value));
</script>

<button
  role="tab"
  onclick={setActiveTab}
  aria-selected={active() == value}
>
  {@render children()}
</button>
