// website/codemos/btn/size.jsx
import { Btn } from "@haze-ui/react";

export default () => {
  return (
    <>
      <Btn className="btn-soft-xs" txt="Success" />
      <Btn className="btn-soft-sm" txt="Success" />
      <Btn className="btn-soft-md" txt="Success" />
      <Btn className="btn-soft-lg" txt="Success" />
      <Btn className="btn-soft-xl" txt="Success" />
    </>
  );
};

// website/codemos/btn/size.svelte
<script lang="ts">
  import { Btn } from "@haze-ui/svelte";
</script>

<div class="flex-(~ gap3 wrap) items-center brd p5 rounded">
  <Btn class="btn-soft-xs" txt="Success" />
  <Btn class="btn-soft-sm" txt="Success" />
  <Btn class="btn-soft-md" txt="Success" />
  <Btn class="btn-soft-lg" txt="Success" />
  <Btn class="btn-soft-xl" txt="Success" />
</div>
