// website/codemos/btn/size.vue
<script setup>
import { Btn } from "@haze-ui/vue";
</script>

<template>
  <Btn class="btn-soft-xs" txt="Success" />
  <Btn class="btn-soft-sm" txt="Success" />
  <Btn class="btn-soft-md" txt="Success" />
  <Btn class="btn-soft-lg" txt="Success" />
  <Btn class="btn-soft-xl" txt="Success" />
</template>

// website/codemos/btn/size.jsx
import { Btn } from "@haze-ui/react";

export default () => {
  return (
    <>
      <Btn className="btn-soft-xs" txt="Success" />
      <Btn className="btn-soft-sm" txt="Success" />
      <Btn className="btn-soft-md" txt="Success" />
      <Btn className="btn-soft-lg" txt="Success" />
      <Btn className="btn-soft-xl" txt="Success" />
    </>
  );
};
