// packages/svelte/components/tabs/index.svelte
<script lang="ts" module>
  export interface CtxProps {
    active: () => string;
    tabLabels: () => string[];
    setActive: (x: string) => void;
    addTabLabel: (x: string[]) => void;
  }
</script>

<script lang="ts">
  import { setContext } from "svelte";
  let { children, defaultValue } = $props();

  let active = $state(defaultValue);
  let tabLabels: string[] = $state([]);

  setContext("tabs", {
    active: () => active,
    tabLabels: () => tabLabels,
    setActive: (x: boolean) => active = x,
    addTabLabel: (x: string) => tabLabels.push(x),
  });
</script>

{@render children()}

// packages/vue/src/tabs/index.vue
<script setup lang="ts">
import type { TabsProps } from "types/tabs";
import { provide, ref } from "vue";

const { defaultValue, value, setValue } = defineProps<TabsProps>();

let active = ref(defaultValue);
let tabLabels = ref<string[]>([]);

const setActive = (x: string) => active.value = x;

provide("tabs", {
  value: value ?? active,
  setValue: setValue ?? setActive,
  tabLabels: tabLabels,
  addTabLabel: (x: string) => tabLabels.value.push(x),
});
</script>

<template>
  <slot />
</template>
