// packages/svelte/src/tabs/list.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import type { CtxProps } from "./index.svelte";

  let { children, class: css } = $props();

  const { value, tabLabels, setValue } = getContext(
    "tabs",
  ) as CtxProps;

  let activeIndex = $derived(tabLabels().indexOf(value()));

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key == "ArrowLeft" && activeIndex != 0) {
      setValue(tabLabels()[activeIndex - 1]);
    } //

    else if (
      e.key == "ArrowRight" && activeIndex != tabLabels().length - 1
    ) {
      setValue(tabLabels()[activeIndex + 1]);
    }
  };

  $effect(() => {
    if (!value()) setValue(tabLabels()[0]);
  });
</script>

<div
  role="tablist"
  class={css?.includes("tabs-") ? css : `tabs ${css}`}
  onkeydown={handleKeyDown}
  tabindex="-1"
>
  {@render children()}
</div>

// packages/vue/src/tabs/list.vue
<script lang="ts" setup>
import { computed, inject, watch } from "vue";
import type { CtxProps } from "./types";

const { class: css = "" } = defineProps<{ class?: string }>();

const { value, tabLabels, setValue } = inject("tabs") as CtxProps;

watch(tabLabels.value, () => {
  if (!value.value) {
    setValue(tabLabels.value[0]);
  }
});

let activeIndex = computed(() => tabLabels.value.indexOf(value.value));

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key == "ArrowLeft" && activeIndex.value != 0) {
    setValue(tabLabels.value[activeIndex.value - 1]);
  } //

  else if (
    e.key == "ArrowRight" && activeIndex.value != tabLabels.value.length - 1
  ) {
    setValue(tabLabels.value[activeIndex.value + 1]);
  }
};
</script>

<template>
  <div
    role="tablist"
    tabindex="-1"
    @keydown="handleKeyDown"
    :class='`${css?.includes("tabs-") ? css : "tabs " + css}`'
  >
    <slot />
  </div>
</template>
