// packages/svelte/components/tabs/list.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import type { CtxProps } from "./index.svelte";

  let { children } = $props();

  const { active, tabLabels, setActive } = getContext("tabs") as CtxProps;

  let activeIndex = $derived(tabLabels().indexOf(active()));

  const handleKeyDown = (e: KeyboardEvent) => {
    e.preventDefault();

    if (e.key == "ArrowLeft" && activeIndex != 0) {
      setActive(tabLabels()[activeIndex - 1]);
    } //

    else if (
      e.key == "ArrowRight" && activeIndex != tabLabels().length - 1
    ) {
      setActive(tabLabels()[activeIndex + 1]);
    }
  };
</script>

<div
  role="tablist"
  class="rounded bg-slate-100 flex p-2"
  onkeydown={handleKeyDown}
  tabindex="0"
>
  {@render children()}
</div>

// packages/vue/src/tabs/list.vue
<script lang="ts" setup>
import { computed, inject, watch } from "vue";
import type { CtxProps } from "./types";

const { class: css = "" } = defineProps<{ class?: string }>();

const { value, tabLabels, setValue } = inject("tabs") as CtxProps;

watch(tabLabels.value, () => {
  if (!value.value) {
    setValue(tabLabels.value[0]);
  }
});

let activeIndex = computed(() => tabLabels.value.indexOf(value.value));

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key == "ArrowLeft" && activeIndex.value != 0) {
    setValue(tabLabels.value[activeIndex.value - 1]);
  } //

  else if (
    e.key == "ArrowRight" && activeIndex.value != tabLabels.value.length - 1
  ) {
    setValue(tabLabels.value[activeIndex.value + 1]);
  }
};
</script>

<template>
  <div
    role="tablist"
    tabindex="-1"
    @keydown="handleKeyDown"
    :class='`${css?.includes("tabs-") ? css : "tabs " + css}`'
  >
    <slot />
  </div>
</template>
